import { useCallback } from 'react';
import type { Language, Localization } from './types';

const translations: Localization = {
  es: {
    title: 'Dashboard de Análisis de Feedback',
    language: 'Idioma',
    spanish: 'Español',
    portuguese: 'Portugués',
    dataSourceTitle: 'Fuente de Datos',
    dataSourceSubtitle: 'La fuente de datos está conectada. Filtra por fecha y analiza.',
    filterByDateTitle: 'Filtrar por Fecha',
    startDate: 'Fecha de Inicio',
    endDate: 'Fecha de Fin',
    analyze: 'Analizar',
    refresh: 'Actualizar',
    analyzing: 'Analizando...',
    loading: 'Cargando y analizando datos...',
    metricsTitle: 'Métricas Clave',
    npsTitle: 'Net Promoter Score (NPS)',
    npsDescription: 'Mide la lealtad del cliente.',
    promoters: 'Promotores',
    passives: 'Pasivos',
    detractors: 'Detractores',
    csatTitle: 'Customer Satisfaction (CSAT)',
    csatDescription: '% de clientes satisfechos (4 o 5).',
    csatService: 'Atención al Cliente',
    csatDelivery: 'Tiempos de Entrega',
    csatPlatform: 'Plataforma',
    sentimentTitle: 'Análisis de Sentimiento',
    sentimentDescription: 'Distribución del sentimiento en los comentarios.',
    positive: 'Positivo',
    neutral: 'Neutral',
    negative: 'Negativo',
    suggestionsTitle: 'Sugerencias de Mejora (IA)',
    suggestionsDescription: 'Acciones generadas por IA a partir del feedback de los clientes.',
    whatWeDidWellTitle: 'Lo que Hicimos Bien',
    whatWeDidWellDescription: 'Comentarios positivos clave identificados por la IA.',
    originalCommentLabel: 'Comentario Original',
    errorTitle: '¡Error!',
    errorNoData: 'No se encontraron datos en la hoja para el rango de fechas seleccionado o el formato es incorrecto.',
    errorSheet: 'No se pudo obtener o procesar la hoja de cálculo. Verifica que el enlace sea público y correcto.',
    errorGemini: 'No se pudo obtener el análisis de la IA.',
    errorSuggestions: 'No se pudieron generar las sugerencias.',
    errorDateRange: 'La fecha de fin no puede ser anterior a la fecha de inicio.',
    errorUnknown: 'Ocurrió un error inesperado.',
    change: 'Cambiar',
  },
  pt: {
    title: 'Dashboard de Análise de Feedback',
    language: 'Idioma',
    spanish: 'Espanhol',
    portuguese: 'Português',
    dataSourceTitle: 'Fonte de Dados',
    dataSourceSubtitle: 'A fonte de dados está conectada. Filtre por data e analise.',
    filterByDateTitle: 'Filtrar por Data',
    startDate: 'Data de Início',
    endDate: 'Data de Fim',
    analyze: 'Analisar',
    refresh: 'Atualizar',
    analyzing: 'Analisando...',
    loading: 'Carregando e analisando dados...',
    metricsTitle: 'Métricas Chave',
    npsTitle: 'Net Promoter Score (NPS)',
    npsDescription: 'Mede a lealdade do cliente.',
    promoters: 'Promotores',
    passives: 'Passivos',
    detractors: 'Detratores',
    csatTitle: 'Customer Satisfaction (CSAT)',
    csatDescription: '% de clientes satisfeitos (4 ou 5).',
    csatService: 'Atendimento ao Cliente',
    csatDelivery: 'Prazos de Entrega',
    csatPlatform: 'Plataforma',
    sentimentTitle: 'Análise de Sentimento',
    sentimentDescription: 'Distribuição do sentimento nos comentários.',
    positive: 'Positivo',
    neutral: 'Neutro',
    negative: 'Negativo',
    suggestionsTitle: 'Sugestões de Melhoria (IA)',
    suggestionsDescription: 'Ações geradas por IA a partir do feedback dos clientes.',
    whatWeDidWellTitle: 'O que Fizemos Bem',
    whatWeDidWellDescription: 'Comentários positivos chave identificados pela IA.',
    originalCommentLabel: 'Comentário Original',
    errorTitle: 'Erro!',
    errorNoData: 'Nenhum dado encontrado na planilha para o intervalo de datas selecionado ou o formato está incorreto.',
    errorSheet: 'Não foi possível obter ou processar a planilha. Verifique se o link é público e está correto.',
    errorGemini: 'Não foi possível obter a análise da IA.',
    errorSuggestions: 'Não foi possível gerar as sugestões.',
    errorDateRange: 'A data de término não pode ser anterior à data de início.',
    errorUnknown: 'Ocorreu um erro inesperado.',
    change: 'Alterar',
  }
};

export const useLocalization = (language: Language) => {
  const t = useCallback((key: string) => {
    return translations[language][key] || key;
  }, [language]);

  return { t };
};